return {
    ["TestingEnemy"] = {
        HP = 4000,
        Speed = 333.33,
        Reward = 2166
    },

    ["TestingEnemy2"] = {
        HP = 5,
        Speed = 4,
        Reward = 7
    },

    ["TestingEnemy3"] = {
        HP = 5,
        Speed = 2,
        Reward = 6
    },

    ["nRat"] = {
        HP = 5,
        Speed = 4,
        Reward = 7
    },

    ["JetRat"] = {
        HP = 4,
        Speed = 15,
        Reward = 11
    }
}